# Generated by Django 3.2.16 on 2022-12-08 09:00

from django.db import migrations, models


def set_order_settings(apps, schema_editor):
    SiteSettings = apps.get_model("site", "SiteSettings")
    Channel = apps.get_model("channel", "Channel")

    site_settings = SiteSettings.objects.first()

    channels = Channel.objects.all()
    for channel in channels:
        channel.automatically_confirm_all_new_orders = (
            site_settings.automatically_confirm_all_new_orders
        )
        channel.automatically_fulfill_non_shippable_gift_card = (
            site_settings.automatically_fulfill_non_shippable_gift_card
        )
        channel.save()


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0005_channel_allocation_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="automatically_confirm_all_new_orders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="automatically_fulfill_non_shippable_gift_card",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_order_settings, migrations.RunPython.noop),
    ]
