# Generated by Django 3.2.16 on 2022-12-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0034_sitesettings_limit_quantity_per_checkout"),
        ("channel", "0007_order_settings_per_channel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="automatically_fulfill_non_shippable_gift_card",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="automatically_confirm_all_new_orders",
        ),
    ]
