# Generated by Django 3.2.16 on 2022-11-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0043_auto_20220922_1146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionevent",
            name="psp_reference",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddConstraint(
            model_name="transactionevent",
            constraint=models.UniqueConstraint(
                fields=("psp_reference", "status"),
                name="TRANSACTION_EVENT_UNQ_PSP_REF_STATUS",
            ),
        ),
    ]
