# Generated by Django 3.2.12 on 2022-02-17 07:57

from django.db import migrations, models

BATCH_SIZE = 10000


def save_order_tokens(apps, schema_editor):
    OrderDiscount = apps.get_model("discount", "OrderDiscount")
    Order = apps.get_model("order", "Order")

    queryset = OrderDiscount.objects.filter(order_id__isnull=False)
    for batch_pks in queryset_in_batches(queryset):
        batch = OrderDiscount.objects.filter(pk__in=batch_pks)
        order_ids = batch.values_list("order_id", flat=True)
        order_id_to_token = {
            id: token
            for id, token in Order.objects.filter(id__in=order_ids).values_list(
                "id", "token"
            )
        }
        for discount in batch:
            discount.order_token = order_id_to_token.get(discount.order_id)

        OrderDiscount.objects.bulk_update(batch, ["order_token"])


def queryset_in_batches(queryset):
    """Slice a queryset into batches.

    Input queryset should be sorted be pk.
    """
    start_pk = 0

    while True:
        qs = queryset.filter(pk__gt=start_pk)[:BATCH_SIZE]
        pks = list(qs.values_list("pk", flat=True))

        if not pks:
            break

        yield pks

        start_pk = pks[-1]


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0032_merge_20211109_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdiscount",
            name="order_token",
            field=models.UUIDField(null=True),
        ),
        # move order relation to order_token field
        migrations.RunPython(save_order_tokens, migrations.RunPython.noop),
        # remove order relation
        migrations.RemoveField(
            model_name="orderdiscount",
            name="order",
        ),
    ]
