# Generated by Django 3.2.12 on 2022-02-15 10:24

import uuid

from django.db import migrations, models
from django.db.models import F


def set_order_number(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    Order.objects.all().update(number=F("id"), use_old_id=True)


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0059_customerevent_order_token"),
        ("order", "0123_update_order_search_document"),
    ]
    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="use_old_id",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="order",
            name="id",
        ),
        migrations.AlterField(
            model_name="order",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.IntegerField(unique=True),
        ),
        migrations.RunSQL("ALTER TABLE order MODIFY COLUMN number INT AUTO_INCREMENT;"),
    ]
